import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SuperTokensProvider } from "@/providers/supertokensProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SuperTokens",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <SuperTokensProvider>
        <body className={`min-h-screen ${inter.className}`}>{children}</body>
      </SuperTokensProvider>
    </html>
  );
}
